### ISSUE TITLE
Weightlessness effects the golden shielded enemies projectiles as well...

### ISSUE THREAD

**Issue by SeanScherer** [danprince/js13k-2022#4]
Maybe this is intended behaviour, but it was a little surprising and frustrating for me the first time I encountered it.

Details: I buy the ritual "weightlessness", and keep playing till I encounter the ememies with the golden shields that fire yellow/golden projectiles. Their projectiles will now cross the entire screen, and cause me to lose health.

I'm not 100% sure, but I have the feeling when this happens, it also causes the bug I mentioned in the licence issue, which is I lose all health, but continue play (seems fair considering the projectiles being fired all the way across the screen, but probably not intended either :P  - guess I should issue a seperate bug for that...).

**Comment by danprince** [comment]
Initially the shields would _bounce_ projectiles back towards Norman, but this ended up way too powerful (easy for Norman to one shot himself, or afflict himself with bleed, or knockback etc) so instead, I made the reflected projectile a separate type that did fixed damage. However, if you have weightlessness on, the projectiles that bounce back are also weightless. This should be an easy fix.

I also noticed the death bug just before I submitted the game, and spotted the same connection between weightlessness and the guards with shields. However, I didn't have time to diagnose it, and I haven't really revisited the codebase since then.

If you figure out what's going on, feel free to send a PR.

**Comment by SeanScherer** [comment]
I was about to write, now that the licence is clear, I'll have a look I think :).

(I'll have to figure out how to get it to run first though, I don't have much experience with web tech).

Thanks for all the pointers though !

**Comment by danprince** [comment]
Fairly easy to get it running in a code sandbox if you want to play around with the codebase without going through any local installations. https://codesandbox.io/s/github/danprince/norman-the-necromancer

**Comment by SeanScherer** [comment]
Thanks, that kinda helped, even if installing wasn't my issue (but rather, knowing what to install :P).

Ended up looking into the "package.json" file, and (though I'm not much of a coder), I can read/use the command line, so I understood I need to look for "Vite" :P.

Just had it running (and played through) on my local machine, so next will be looking into this issue and other stuff !

**Comment by AshSimmonds** [comment]
PR'd:  
  
- https://github.com/danprince/norman-the-necromancer/pull/5

**Comment by danprince** [comment]
Should be fixed as of #5. Feel free to re-open if you see otherwise during gameplay though!

**Comment by AshSimmonds** [comment]
Well FWIW  #5 fixed the ghosty not dying bug, but not the weightlessness behaviour - whether that's a desired outcome or not. I kinda think it's an interesting side-effect, because weightless is too OP so there needs to be some kind of footgun to it.

**Comment by danprince** [comment]
@AshSimmonds yeah, the royal guards are supposed to be the counter to some of the OP spells, so that you have to be a bit careful to shoot when they're walking.

The whole game just needs a ton of balancing though, but the only problem that was actually bothering me was being able to win after dying, as described above.

**Comment by SeanScherer** [comment]
@AshSimmonds , nice, thanks for fixing :) !

On the weightlessness - I understand now that's intended behaviour, so yes, a question of either balance or gameplay mechanics, rather than a real bug.

Talking of which :P ... on the question of balance, I've been spending most of my free time the last days either playing or modding the game, so I was going to ask if there's any place that's more convenient if I'd like to ask some questions / discuss stuff (eg, are you on any Discord or Matrix servers I could head over to @danprince ?).

**Comment by danprince** [comment]
Started a Discord server for anyone who's interested: https://discord.gg/deQq84tcEJ
